### ISSUE TITLE
[Lesson 0] 시작해볼까요?

### ISSUE THREAD

**Issue by huinalam** [Choiyos/CSharpWpfLession#1]
# [Lesson 0] 시작해볼까요?

레슨을 시작해볼까요 :)

C# WPF Application으로 프로젝트를 시작하여. 'hello world'를 출력하는 코드를 구현 후. push해주세요.
1. 'gitignore'이란 게 있습니다. 이를 공부해보시고, 이 프로젝트에 적용해주세요.
2. 완료 후 댓글로 간단한 설명도 달아주시구요.
3. view의 구성은 자유롭게 구성한다.

**Comment by Choiyos** [comment]
gitignore 적용과 hello world 출력 프로젝트 Push 완료했습니다.

**Comment by huinalam** [comment]
gitinore 설정하는데서 다들 어려움을 겪는데, 잘 하셨네요 ㅎㅎ
아래의 질문에 답변해주시겠어요?

1. .gitignore이 어떤 용도로 사용하는지 간략하게 설명해주시겠어요?
2. .gitignore template를 찾아보시면 관련 정보가 많은데요. 이런게 왜 필요한걸까요? 그리고 지금 적용된 gitignore과 어떤 차이점이 있는지 생각해보세요.

**Comment by Choiyos** [comment]
1. gitIgnore는 git버전관리에서 제외할 파일들을 지정하고싶을 때에 사용합니다. 프로젝트 설정 파일이나 로그 파일 등이 버전관리에서 대표적으로 제외하는 파일들입니다.

2. gitignore template가 필요한 이유는 프로젝트마다 사용하는 기술 스택이 다르다면, 프로젝트 설정 파일이나 컴파일 혹은 실행중에 나오는 로그들도 다르기 때문에 다른 gitignore의 세팅을 해주어야 하기 때문입니다.
지금 적용된 gitignore은 주로 비주얼 스튜디오의 프로젝트에 공용으로 쓰이는 세팅이며, 만약 유니티 프로젝트의 경우, 유니티 에디터 설정파일 확장자 등을 gitignore에 추가해주어야 합니다.

**Comment by huinalam** [comment]
빠른 마무리 ^^
