### ISSUE TITLE
[Lesson 10] Test Code 구현하기

### ISSUE THREAD

**Issue by huinalam** [Choiyos/CSharpWpfLession#10]
# [Lesson 10] Test Code 구현하기

기존 프로그램의 코드 모듈에 대한 테스트 코드를 구현한다.

- 제한사항
  - MSTest 기반으로 작성한다. (기호에 따라 XUnit등을 활용해도 좋다)
  - 테스트코드는 AAA패턴으로 구현한다.
  - 이후 모든 코드는 테스트 코드를 작성할 수 있도록 구현한다.

- 힌트
  - 테스트 코드는 정상적인 동작 방식을 보장, 프로그램의 점진적 설계, 다른 사람이 코드를 사용하고자 할 때 구현의 의도를 알리려는 목적으로 작성이 된다.

- 힌트 코드
```
[TestMethod]
public void CreateStar() 
{
  // Arrange
  var validResult = "* ** ***";
  var parttern = new StarParttern();
  
  // Act
  var result = parttern.Build(5);

  // Assert
  Assert.Equal(validResult, result)
}
```

**Comment by Choiyos** [comment]
패턴 생성에 대한 테스트코드 작성하여 Push했습니다.
