### ISSUE TITLE
[Lesson 11] 이전 패턴 보기 강화

### ISSUE THREAD

**Issue by huinalam** [Choiyos/CSharpWpfLession#11]
# [Lesson 11] 이전 패턴 보기 강화

이전 패턴 기록을 보는 방식에 대해 요청사항이 많아졌다.
요청사항은 아래와 같다.
- 이전 패턴 보기를 100개로 보인다.
- 2, 5, 10칸씩 이동이 가능하다.
- 특정 기록의 데이터를 수정하여 볼 수 있어야 한다.
  - 가령, 10번째 별모양을 다른 별모양으로 수정. 혹은 개수 조정.

### 제한사항
- 기능 구현 후, 기능에 대한 테스트 코드를 작성한다.

**Comment by Choiyos** [comment]
Push 완료하였습니다.

**Comment by huinalam** [comment]
https://github.com/Choiyos/CSharpWpfLession/commit/582ad4aea44385c4767a7e0980bb3c1896ccd1d8

리뷰 올려두었습니다. 다 리뷰한건 아니라서, 다음에 딥토크해보지요.

**Comment by Choiyos** [comment]
피드백에 대한 사항 수정하여 Push했습니다.
