### ISSUE TITLE
[Final Lesson] 문서화 작업

### ISSUE THREAD

**Issue by huinalam** [Choiyos/CSharpWpfLession#13]
# [Final Lesson] 문서화 작업

작업한 코드를 다른 개발자가 읽고 활용할 수 있도록 wiki 문서를 작성한다.

1. 오픈소스들 중에 github wiki를 활용하여 문서화한 프로젝트를 3개 이상 찾아본다(꼭 wiki형식이 아니어도 좋다.). 그 중에서 본인이 생각하기에 가장 문서화를 잘 했다고 생각하는 프로젝트를 선정하고, 그 이유에 대해 답한다.
2. 문서화 작업을 한다.
3. 소스코드에 필요한 주석을 추가한다.

**Comment by Choiyos** [comment]
MongoDB
 - Documentation 사이트를 따로 만들어서 Platform별로 사용법을 문서화 시켜놓았음.
	Driver의  경우는 언어별로 정리하여 설치법부터 버전별 지원가능여부, Usage가 포함된 Git Repo의 링크를 연결시켰음.
	
NLog
 - Wiki에 Framework별 Getting Started부터 목적별 구성요소 용법, 추가기능과 확장프로그램 연결까지 모든 것을 목차에 링크로 잘 정리하였음.
 
RestSharp
 - README.md에서는 프로젝트의 최근 이슈(이미 사용하는 사람 중 가장 관심이 많을)에 대해서 다루고있었고, 처음 접하는 사람들을 위한 문서화는 wiki에 해두었다. 여러 응용된 사용법과 향후 개발 기능, 추천 사용법 등으로 구분해놓은 것이 인상적이었다.
 
modular-monolith-with-ddd
 - DDD에 대한 정의부터 유닛 테스트 가이드라인까지 제공하는 폭넓은 목차를 가지고있으며, 구조를 표현하기 위한 많은 Diagram을 제공하고 있다. 만약 이 프로젝트의 구조대로 작업을 한다면, 웬만한 이슈에 있어서는 구글링 할 필요 없이 문서화된 정보만으로 해결할 수 있을 것 같다.
 
typeScript
 - 언어에 대한 가장 기초적인 설명부터 여러 응용, 추가기능까지 마소답게 깔끔한 구성으로 문서화를 시켜놓은 것 같다.
 
기타 깔끔하다고 생각했던 Repo : khaiii, create-react-app
