### ISSUE TITLE
[Lesson 1] 첫 Pattern

### ISSUE THREAD

**Issue by huinalam** [Choiyos/CSharpWpfLession#2]
# [Lesson 1] 첫 Pattern

아래와 같이 표시되도록 코드를 작성해보세요.
 
```
* 
**
***
****
***** 
```

- 제한조건
  - hello world를 구현한 프로젝트 코드를 수정해서 만든다.
  - view의 구성은 자유롭게 구성한다.

**Comment by Choiyos** [comment]
Push 완료했습니다.

**Comment by huinalam** [comment]
https://github.com/Choiyos/CSharpWpfLession/commit/0048ec66aa78b14087e13b03a32ea7fb8174be2d#r34843409

리뷰를 달았습니다 :)

**Comment by huinalam** [comment]
좋아요 마무리 ^^
