### ISSUE TITLE
[Lesson 2] 사용자가 입력가능하도록 만든다.

### ISSUE THREAD

**Issue by huinalam** [Choiyos/CSharpWpfLession#3]
# [Lesson 2] 사용자가 입력가능하도록 만든다.

Lesson 1의 프로젝트를 수정하여 사용자가 몇 줄을 찍을 것인지 할 수 있도록 한다.

``` 
How many lines? (1..100)  7
*
**
***
****
*****
******
******* 
```

- 제한조건
  - 사용자는 1 부터 100 까지의 값을 칠 수 있다. 
  - 사용자가 0 이나 마이너스 값을 치는 경우에는 아래와 같이 표시하고 input 을 다시 요구한다. 100 보다 큰 경우에도 마찬가지이다.
  - 사용자가 정상 값을 칠 때까지 계속 입력을 받는다.
  - 입력 방식은 스스로 제안한다.

**Comment by Choiyos** [comment]
Push 완료했습니다.

**Comment by huinalam** [comment]
잘 하셨습니다. 텍스트 높이를 측정해서 표현한 점이 재미있네요 ㅎㅎ

몇가지 이슈가 있는데요.

1. 100을 입력했을 때, 별들이 한눈에 안보이는 이슈가 있습니다.
2. 20 입력 후, 10으로 돌아갔을 때, 윈도우 크기가 커진 상태에서 그대로 인 점이 아쉽네요. 사용자가 보기에 일관성이 없달까요? 다시 작게 수정되거나, 다른 방법을 제안해주세요.

**Comment by Choiyos** [comment]
이슈에 대한 해결방안으로 윈도우 크기를 조정하지 않고 스크롤 뷰어를 추가함으로써 100을 입력했을 경우의 별을 모두 볼 수 있게하고, 작은 값을 입력시 사용자가 윈도우를 직접 컨트롤 할 일이 없도록 수정했습니다.

**Comment by huinalam** [comment]
깔끔한 마무리 ^^
