### ISSUE TITLE
[Lesson 3] 새로운 Pattern

### ISSUE THREAD

**Issue by huinalam** [Choiyos/CSharpWpfLession#4]
# [Lesson 3] 새로운 Pattern

아래의 2 가지 Pattern 을 추가하고 (총 3 개의 Pattern 이 된다)
사용자가 원하는 Pattern 을 선택할 수 있도록 한다. 

```
- Pattern 추가
*****
 ****
  ***
   **
    * 
 
- Pattern 추가
   *
  ***
 *****
  ***
   * 
```

- 제한사항
  - 잘못된 Input 이 들어오면 다시 입력을 받도록 한다.
  - Input 입력방법은 정해져 있지 않다.
  - 사용자가 이해하기 쉬운 것을 제안하라.
  - 다이아몬드 형태의 입력은 홀수만 입력되도록 한다.
  - 정상적으로 선택한 후 종료한다.

**Comment by Choiyos** [comment]
[정상적으로 선택한 후 종료한다.]
에 대한 간단한 부연설명좀 해주실 수 있나요?

**Comment by huinalam** [comment]
`정상적으로 선택한 후 종료한다.` 해당 사항은 필요가 없겠네요. 생략하고 진행해주세요^^

**Comment by Choiyos** [comment]
Push 완료했습니다.

**Comment by huinalam** [comment]
리뷰 남겼습니다 ^^

https://github.com/Choiyos/CSharpWpfLession/commit/fdc38c51c531c7a9d9e84aebfe596ae357cbbadd
