### ISSUE TITLE
[Lesson 4] 무한 Loop 및 Pattern 추가 

### ISSUE THREAD

**Issue by huinalam** [Choiyos/CSharpWpfLession#5]
# [Lesson 4] 무한 Loop 및 Pattern 추가 

한번 하고 종료되지 않고, 계속 Loop 를 돌도록 만든다.
아울러, 아래의 Pattern 을 추가한다. 
 
```
- Pattern 추가
   ***
  ***
 *** 
 
- Pattern 추가
   ***
  **
 * 
```

- 제한사항
  - 사용자가 이해하기 쉬운 화면을 제안한다.

**Comment by Choiyos** [comment]
Push 완료했습니다.

**Comment by Choiyos** [comment]
이슈 수정 Push했습니다.

**Comment by huinalam** [comment]
![image](https://user-images.githubusercontent.com/4952867/63909987-e8ec1280-ca5f-11e9-9236-ef10e293bf7c.png)

101을 입력했더니 화면에 엉뚱한 화면이 뜨네요ㅎㅎ

**Comment by huinalam** [comment]
https://github.com/Choiyos/CSharpWpfLession/commit/69070b51186250b4728f8fc1cbbe1db460b364a4

리뷰 남겼습니다 ^^

**Comment by huinalam** [comment]
![image](https://user-images.githubusercontent.com/4952867/63910247-d9b99480-ca60-11e9-92af-0d363c931a94.png)
![image](https://user-images.githubusercontent.com/4952867/63910316-28672e80-ca61-11e9-834b-fb20ab5b5da8.png)

사용하다보니 조금 불편한 점이 있는데요..
다시 select를 눌러서 선택하려할 때, Pattern1으로 초기화 되어있는게 뭔가 불편하네요.
이 점을 개선해주시겠어요?

**Comment by Choiyos** [comment]
이슈 수정하여 Push했습니다.
