### ISSUE TITLE
[Lesson 6] Library로 만들기

### ISSUE THREAD

**Issue by huinalam** [Choiyos/CSharpWpfLession#6]
# [Lesson 6] Library로 만들기

메인부분을 제외한 입력부분과 수행부분을 라이브러리로 만들고, 메인 프로젝트가 라이브러리를 reference로 참조하여 사용하게 만든다. 라이브러리 이름은 스스로 정한다.

참고) Lesson5는 서로 리뷰해주는 과정인데, 이미 진행하였으므로 스킵합니다. ^^

**Comment by Choiyos** [comment]
Push 완료하였습니다.

**Comment by Choiyos** [comment]
.NET Standard : .NET portable의 표준화된 API스펙으로, 이식성을 계승하고 파편화문제를 개선한 .NET API 정규화 스펙이다. .NET Framework와 Core 모두 Standard를 계승하여 만들어진 플랫폼이다.

.NET Framework : .NET Standard를 계승하여 만들어진 플랫폼. 윈도우 전용이며, 다양한 기능과 확장을 지원한다. Standard Library 2.0을 공유한다.

.NET Core : Standard의 API 스펙을 따르면서 새로운 기능을 추가한 플랫폼으로, 경량화되어 윈도우, 리눅스, 맥에서 사용 가능하다. Standard Library 2.0을 공유한다.

솔루션 통합하여 PUSH했습니다.

**Comment by huinalam** [comment]
완료 되었으므로 종료 ^^
