### ISSUE TITLE
[Lesson 7] 이전 패턴 기록

### ISSUE THREAD

**Issue by huinalam** [Choiyos/CSharpWpfLession#7]
# [Lesson 7] 이전 패턴 기록
- 한번 출력된 이전 패턴이 기록되어 보여야 한다.
- 최소 1개 ~ 최대 10개까지 확인할 수 있도록 세팅이 가능하다.

제한사항
사용자가 이해하기 쉬운 화면을 제안한다.

**Comment by Choiyos** [comment]
Push 완료했습니다.

**Comment by huinalam** [comment]
https://github.com/Choiyos/CSharpWpfLession/commit/202cb3a6bfd6b908a0b45877cd1723ae77899223

리뷰를 적었습니다. 크게는 History라는 표현이 좀 애매하지 않나 하는 생각이 드는데요.
한번 고민해보시고요 ^^

**Comment by Choiyos** [comment]
해당 이슈들 정리하여 Push했습니다!

**Comment by huinalam** [comment]
수고하셨습니다 ^^
