### ISSUE TITLE
[Lesson 9] 새 Pattern 추가 

### ISSUE THREAD

**Issue by huinalam** [Choiyos/CSharpWpfLession#9]
# [Lesson 9] 새 Pattern 추가 

아래의 Pattern 을 추가한다.

```
*     *      *       
      **     **
             *** 
```

- 제한사항
  - 각 Pattern 간의 간격은 일정하도록 한다.  입력된 줄 + 2 줄 
  - 표현이 길어질 때, 어떻게 표현하면 좋을 지 고민해본다.

**Comment by Choiyos** [comment]
Push 완료했습니다.

**Comment by huinalam** [comment]
https://github.com/Choiyos/CSharpWpfLession/commit/faf7be239644b895e286cb5460541390c1b4729d
리뷰 남겼습니다~
